
package org.test;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnvioDoc", targetNamespace = "http://test.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnvioDoc {


    /**
     * 
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValor", targetNamespace = "http://test.org/", className = "org.test.GetValor")
    @ResponseWrapper(localName = "getValorResponse", targetNamespace = "http://test.org/", className = "org.test.GetValorResponse")
    @Action(input = "http://test.org/EnvioDoc/getValorRequest", output = "http://test.org/EnvioDoc/getValorResponse")
    public byte[] getValor();

}
